version: '3.8'
services:
  app-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5429:5432'
    volumes:
      - db:/var/lib/postgresql/application/data

volumes:
  db:
    driver: local
